<?php
// Enable CORS
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");
header("Content-Type: application/json");

// Handle preflight requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Start session
session_start();

// This file is generated by Composer and loads all installed libraries (like JWT).
require_once __DIR__ . '/vendor/autoload.php';

define('ROOT_PATH', __DIR__);

// Autoload classes
spl_autoload_register(function ($class_name) {
    $directories = ['controllers/', 'models/', 'services/', 'utils/'];
    foreach ($directories as $directory) {
        $file = $directory . $class_name . '.php';
        if (file_exists($file)) {
            require_once $file;
            return;
        }
    }
});

// Route requests
$endpoint = $_GET['endpoint'] ?? '';

switch ($endpoint) {
    case 'notification':
        $controller = new NotificationController();
        $controller->handleRequest();
        break;
        
    case 'email':
        $controller = new EmailController();
        $controller->handleRequest();
        break;
        
    case 'auth':
        $controller = new AuthController();
        $controller->handleRequest();
        break;

    case 'job':
        $controller = new JobController(); 
        $controller->handleRequest();
        break;
        
    default:
        http_response_code(404);
        echo json_encode(['error' => 'Endpoint not found']);
        break;
}